/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-04-16 08:48:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inspection;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inspection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1643079176937L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("table.dataTable tbody td {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dataTables_filter input {\r\n");
      out.write("\tborder-width: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.dataTable tbody tr:hover {\r\n");
      out.write("\tbackground-color: #eaf2f3 !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\t// 예약 테이블  row 클릭 이벤트 > 환자상세정보 셋팅\r\n");
      out.write("\t$(\"#yeyakTb\").on('click', 'tbody tr', function () {\r\n");
      out.write("\t\tvar row = $(\"#yeyakTb\").DataTable().row($(this)).data();\r\n");
      out.write("\t\tfnSelectDetailMedical(row);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar csrfParameter = $(\"meta[name=_csrf_parameter]\").attr(\"content\");\r\n");
      out.write("\tvar csrfHeader = $(\"meta[name=_csrf_header]\").attr(\"content\");\r\n");
      out.write("\tvar csrfToken = $(\"meta[name=_csrf]\").attr(\"content\");\r\n");
      out.write("    var data = {};\r\n");
      out.write("    data['treatCd'] = $(\"#treatCd\").text();\r\n");
      out.write("    data[csrfParameter]=csrfToken;\r\n");
      out.write("    \r\n");
      out.write("//     var inspectionList = \"\";\r\n");
      out.write("//     console.log(\"treatCd>>>\",$(\"#treatCd\").text());\r\n");
      out.write("// \t$.ajax({\r\n");
      out.write("// \t\ttype: 'post',\r\n");
      out.write("// \t\tdataType : 'json',\r\n");
      out.write("// \t\tdata: data,\r\n");
      out.write("// \t\turl: '/inspection',\r\n");
      out.write("// // \t\ttraditional: true,\r\n");
      out.write("// \t\tasync:false,\r\n");
      out.write("// \t\tsuccess: function(data){\r\n");
      out.write("// \t\t\t$.each(data,function(i,v){\r\n");
      out.write("// \t\t\t\tinspectionList += '<div class=\"table-row\" id=\"insptbl_row\"'+i+' style=\"display: table-row;\">' \r\n");
      out.write("// \t\t\t\tinspectionList +='<div class=\"table-cell\" id=\"tbl_cell\" style=\"display: table-cell; width: 20%;\">'+v.rownum +'</div>';\r\n");
      out.write("// \t\t\t\tinspectionList +='<div class=\"table-cell\" id=\"tbl_cell\" style=\"display: table-cell; width: 10%;\">'+v.inspNm +'</div>';\r\n");
      out.write("// // \t\t\t\tinspectionList +='<div class=\"table-cell\" id=\"tbl_cell\" style=\"display: table-cell; width: 10%;\">'+v. +'</div>';\r\n");
      out.write("// // \t\t\t\tinspectionList +='<div class=\"table-cell\" id=\"tbl_cell\" style=\"display: table-cell; width: 20%;\">'+v +'</div>';\r\n");
      out.write("// // \t\t\t\tinspectionList +='<div class=\"table-cell\" id=\"tbl_cell\" style=\"display: table-cell; width: 40%;\">'+v +'</div>';\r\n");
      out.write("// \t\t\t\tinspectionList +='</div>'\r\n");
      out.write("// \t\t\t})\r\n");
      out.write("// \t\t\t$(\"#loginUser\")\r\n");
      out.write("// \t\t\t$(\"#symptoms\").append(inspectionList);\r\n");
      out.write("// \t\t\tconsole.log(\"data>>>>\",data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t}\r\n");
      out.write("// \t})\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfnSetDataYeyekTable();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("const fnSetDataYeyekTable = () => {\r\n");
      out.write("\t$('#yeyakTb').DataTable({\r\n");
      out.write("\t\t\"data\": ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inspWaitList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("\t\t\"dataSrc\": \"\",\r\n");
      out.write("\t\t\"columns\": [\r\n");
      out.write("\t\t\t{ 'data': 'rownum', \"className\": \"text-center\" },\r\n");
      out.write("\t\t\t{ 'data': 'pntNm', \"className\": \"text-center\" },\r\n");
      out.write("\t\t\t{ 'data': 'pntPrno', \"className\": \"text-center\" },\r\n");
      out.write("\t\t],\r\n");
      out.write("\t\t\"bLengthChange\": false, // thought this line could hide the LengthMenu\r\n");
      out.write("\t\t\"pageLength\": 5,\r\n");
      out.write("\t\t\"language\": {\r\n");
      out.write("\t\t\t\"emptyTable\": \"현재 대기환자가 없습니다.\",\r\n");
      out.write("\t\t\t\"info\": \"총 _TOTAL_명   _START_에서 _END_까지 표시\",\r\n");
      out.write("\t\t\t\"search\": \"환자검색 : \",\r\n");
      out.write("\t\t\t\"zeroRecords\": \"일치하는 환자가 없습니다.\",\r\n");
      out.write("\t\t\t\"paginate\": {\r\n");
      out.write("\t\t\t\t\"first\": \"처음\",\r\n");
      out.write("\t\t\t\t\"last\": \"마지막\",\r\n");
      out.write("\t\t\t\t\"next\": \"다음\",\r\n");
      out.write("\t\t\t\t\"previous\": \"이전\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const fnSelectDetailMedical = (row) => {\r\n");
      out.write("// \tconsole.log(row);\r\n");
      out.write("\t$(\"#pntNm\").text(row.pntNm);\r\n");
      out.write("\trow.pntSex == 'M' ? $(\"#sex\").text('남') : $(\"#sex\").text('여');\r\n");
      out.write("\t$(\"#pntPrno\").text(row.pntPrno);\r\n");
      out.write("\t$(\"#age\").text(row.age);\r\n");
      out.write("\t$(\"#secNm\").text(row.secNm);\r\n");
      out.write("\t$(\"#pntCd\").val(row.pntCd);\r\n");
      out.write("\t$(\"#treatCd\").text(row.treatCd);\r\n");
      out.write("\t$(\"#rcptNo\").val(row.rcptNo);\r\n");
      out.write("\t\r\n");
      out.write("\tvar inspectionList = \"\";\r\n");
      out.write("\t$.each(row.inspectionVO,function(i,v){\r\n");
      out.write("// \t\tconsole.log(i);\r\n");
      out.write("\t\tinspectionList += '<div class=\"table-row insptbl_low\" id=\"insptbl_row'+i+'\" style=\"display: table-row; cursor:pointer;\" >' \r\n");
      out.write("\t\tinspectionList += '<label id=\"insplbl\"><input type=\"radio\" name=\"inspRadioBtn\" value=\"'+i+'\" style=\"display:none\" '\r\n");
      out.write("\t\tinspectionList += 'inspTypeCd=\"'+ v.inspTypeCd + '\" inspCd=\"'+ v.inspCd + '\" inspAmt=\"'+ v.inspAmt + '\"></label>'\r\n");
      out.write("\t\tinspectionList +='<div class=\"table-cell\" id=\"inspNm'+i+'\" style=\"display: table-cell; width: 50%;\">'+v.inspNm +'</div>';\r\n");
      out.write("\t\tinspectionList +='<div class=\"table-cell\" id=\"secNm\" style=\"display: table-cell; width: 25%;\">'+row.secNm +'</div>';\r\n");
      out.write("\t\tinspectionList +='<div class=\"table-cell\" id=\"empNmDoc\" style=\"display: table-cell; width: 25%;\">'+row.empNm +'</div>';\r\n");
      out.write("\t\tinspectionList +='</div>'\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\"#inspectionList\").html(inspectionList);\r\n");
      out.write("\t\r\n");
      out.write("\tvar fileDiv =\"\";\r\n");
      out.write("\tfor(var i=0; i<$(\".insptbl_low\").length;i++){\r\n");
      out.write("\t\tfileDiv += '<div class=\"form-control rounded fileDiv\" id=\"fileDiv'+i+'\" style=\"height:80px; display:none;\" >'\r\n");
      out.write("\t\tfileDiv += '</div>'\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#filePlus\").html(fileDiv);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main_content_iner \">\r\n");
      out.write("\t<div class=\"container-fluid p-0\">\r\n");
      out.write("\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"messages_box_area\">\r\n");
      out.write("\t\t\t\t\t<div class=\"messages_list\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"white_box shadow-sm mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message_pre_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messges_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"mb-3\">대기환자</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table\" id=\"yeyakTb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">성함</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">생년월일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"messages_list mb_30\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"frm\" name=\"frm\" class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"white_box shadow-sm mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message_pre_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"messges_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"mb-3\">환자정보</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mr-3\">성함</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:50px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"pntNm\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mx-3\">성별</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:50px\" id=\"sex\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mx-3\">생년월일</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:80px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"pntPrno\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mx-3\">나이</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:50px\" id=\"age\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mx-3\">진료과</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:50px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"secNm\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-inline mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mr-3\">진료코드</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;\" id=\"treatCd\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"rcptNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message_pre_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"messges_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"mb-3\">검사 요청내역</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"\" id=\"rsvtNo\" name=\"rsvtNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"symptoms\" name=\"symptoms\" class=\"form-control rounded\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t style=\"resize:none;height:139px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taria-label=\"Small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"table\" style=\"display: table;\" id=\"inspectionList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"white_box shadow-sm\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message_pre_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messges_info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"mb-3\">검사</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"messages_chat\" style=\"height:auto; overflow:hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mr-3\">담당자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:100px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"empCd\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.empNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"label-title px-4 py-1 mx-3\">검사일시</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"py-1\" style=\"color:#828bb2;min-width:50px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"cmntDt\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group file-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pntCd\" id=\"pntCd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"custom-file\" style=\"height:auto; overflow:auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"custom-file-input\" id=\"inputFile\" multiple=\"multiple\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"custom-file-label\" for=\"inputGroupFile02\">결과 파일 선택</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"filePlus\" style=\"height:80px\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-outline-secondary px-4\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:fnSaveFile();\">전송</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger px-4\" type=\"button\" id=\"deletefile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"javascript:fnDeleteFile();\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"text-right mt-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-pill px-5\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"endInsp\">검사 마치기</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"white_box shadow-sm imgViewDiv\" id=\"imgViewDiv\" style=\"z-index : 1080;display:none;position:absolute; top:150px;left:500px;width:1000px;\">\r\n");
      out.write("\t <button type=\"button\" id=\"viewImgClose\" class=\"btn btn-danger\" style=\"float:right;\">×</button>\r\n");
      out.write("\t<div id=\"viewBigImg\" style=\"border : 3px solid black; height : 300px;width:95%; margin : 20px\"></div>\r\n");
      out.write("\t<div id=\"viewImgList\" style=\"border : 3px solid black; height : 100px;width:95%; margin : 20px\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("var saveList = [];\r\n");
      out.write("var saveMap\r\n");
      out.write("var imgs = [];\r\n");
      out.write("\r\n");
      out.write("$(\".custom-file\").on(\"click\",function(){\r\n");
      out.write("\tif($('input[name=\"inspRadioBtn\"]:checked').length ==0){\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\tswal(\"알림\",\"검사요청내역을 선택해주세요\",\"warning\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\"#endInsp\").on('click',function(){\r\n");
      out.write("\tvar treatCd = $(\"#treatCd\").text();\r\n");
      out.write("\tif(treatCd==''){\r\n");
      out.write("\t\tswal('','환자를 선택해주세요.','warning');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar pntCd = $(\"#pntCd\").val();\r\n");
      out.write("\tdata = {\"pntCd\" : pntCd};\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:'/osDaegi',\r\n");
      out.write("\t\ttype:'post',\r\n");
      out.write("\t\tdata:data,\r\n");
      out.write("\t\tbeforeSend: function (jqXHR, settings) {\r\n");
      out.write("\t\t\t/* ajax 사용시 헤더에 스프링시큐리티 토큰 설정 */\r\n");
      out.write("\t\t\tvar token = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\tvar header = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\tjqXHR.setRequestHeader(header, token);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess: function(res){\r\n");
      out.write("\t\t\tif(res){\r\n");
      out.write("\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(document).on(\"click\",\".table-row\",function(){\r\n");
      out.write("\tvar today = new Date();\r\n");
      out.write("\ttoday = getFormatDate(today);\r\n");
      out.write("// \ttoday = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate()+' '+today.getHours()+':'+today.getMinutes()+':'+today.getSeconds();\r\n");
      out.write("// \tconsole.log($(this).children(\"#inspRadioBtn\"))\r\n");
      out.write("// \tconsole.log($(this).find($('input[name=\"inspRadioBtn\"]'))[0])\r\n");
      out.write("\t$(this).find($('input[name=\"inspRadioBtn\"]')).prop(\"checked\",true);\r\n");
      out.write("// \t$(this).find($('input[name=\"inspRadioBtn\"]'))[0].checked=true;\r\n");
      out.write("// \talert($(this).find($('input[name=\"inspRadioBtn\"]')).prop(\"checked\"));\r\n");
      out.write("\t$(this).children().first().attr(\"style\",\"display:none\")\r\n");
      out.write("// \tconsole.log(\"지금찍은 RadioButton의 checked된 value\",$(this).find($('input[name=\"inspRadioBtn\"]:checked')).val())\r\n");
      out.write("\tvar empCd = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\tvar treatCd = $(\"#treatCd\").text();\r\n");
      out.write("\tvar rcptNo = $(\"#rcptNo\").val();\r\n");
      out.write("\tfor(var i = 0; i < $('input[name=\"inspRadioBtn\"]').length; i++){\r\n");
      out.write("\t\tvar radioThis = $('input[name=\"inspRadioBtn\"]')[i];\r\n");
      out.write("\t\tvar inspTypeCd = $(radioThis).attr('insptypecd');\r\n");
      out.write("\t\tvar inspCd = $(radioThis).attr('inspcd');\r\n");
      out.write("\t\tvar inspAmt = $(radioThis).attr('inspamt');\r\n");
      out.write("\t\tvar inspNm = $(\"#inspNm\" + i).text();\r\n");
      out.write("\t\tvar map = {}\r\n");
      out.write("\t\tsaveList.push(map)\r\n");
      out.write("\t\tsaveList[i].inspNm = inspNm;\r\n");
      out.write("\t\tsaveList[i].inspTypeCd = inspTypeCd;\r\n");
      out.write("\t\tsaveList[i].inspCd = inspCd;\r\n");
      out.write("\t\tsaveList[i].inspAmt = inspAmt;\r\n");
      out.write("\t\tsaveList[i].empCd = empCd;\r\n");
      out.write("\t\tsaveList[i].treatCd = treatCd;\r\n");
      out.write("\t\tsaveList[i].rcptNo = rcptNo;\r\n");
      out.write("\t\tsaveList[i].base64img = imgs[i];\r\n");
      out.write("\t}\r\n");
      out.write("\tvar regexToday = today.replace(/(\\-|\\/|\\s|\\:)/g,\"\")\r\n");
      out.write("\tsaveList[$('input[name=\"inspRadioBtn\"]:checked').val()].inspDt = regexToday;\r\n");
      out.write("// \tconsole.log(saveList);\r\n");
      out.write("\t$(\"#cmntDt\").empty();\r\n");
      out.write("\t$(\"#cmntDt\").append(today);\r\n");
      out.write("\t$(\".table-row\").attr(\"style\",\"border : 3px solid black\")\r\n");
      out.write("\t$(this).attr(\"style\",\"background-color:gray\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar radioVal = $(this).find($('input[name=\"inspRadioBtn\"]:checked')).val();\r\n");
      out.write("\t$(\".fileDiv\").hide();\r\n");
      out.write("\t$(\"#fileDiv\"+radioVal).show();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(\"#inputFile\").on(\"change\", imgPreview);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("function imgPreview(e){\r\n");
      out.write("// \tconsole.log(\"e.target>>>\",e.target);\r\n");
      out.write("// \talert(\"hi\")\r\n");
      out.write("// \t$(\"#inputFile\").val(\"\");\r\n");
      out.write("\tvar files = e.target.files;\r\n");
      out.write("\tvar fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("\t\r\n");
      out.write("// \tconsole.log(fileArr);\r\n");
      out.write("\tvar img = []\r\n");
      out.write("\tfileArr.forEach(function(f){\r\n");
      out.write("\t\tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t\talert(\"이미지만 가능합니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar reader = new FileReader();\r\n");
      out.write("\t\treader.onload = function(e){\r\n");
      out.write("// \t\t\t$(\"#filesList\").css({\"background\":\"url('\"+e.target.result+\"')\"\r\n");
      out.write("// \t\t\t,\"background-repeat\":\"no-repeat\"\r\n");
      out.write("// \t\t\t,\"background-size\":\"100%\"\r\n");
      out.write("// \t\t\t,\"background-position\":\"center\"}); \r\n");
      out.write("\t\t\tvar img_html = \"<img src=\\\"\" + e.target.result + \"\\\" style='width:100px;' class='viewImg'/>\";\r\n");
      out.write("\t\t\timg.push(e.target.result);\r\n");
      out.write("\t\t\tvar radioVal = $('input[name=\"inspRadioBtn\"]:checked').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#fileDiv\"+radioVal).append(img_html);\r\n");
      out.write("// \t\t\t$(\"#filesList\").clone()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treader.readAsDataURL(f);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\timgs.push(img);\r\n");
      out.write("// \tconsole.log(imgs);\t\t\r\n");
      out.write("}\r\n");
      out.write("function fnDeleteFile(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar RadioVal = $('input[name=\"inspRadioBtn\"]:checked').val();\r\n");
      out.write("\timgs = [];\r\n");
      out.write("// \tconsole.log(RadioVal)\r\n");
      out.write("\t$(\"#fileDiv\"+RadioVal).empty();\r\n");
      out.write("}\r\n");
      out.write("function fnSaveFile(){\r\n");
      out.write("\tif(saveList.length == 0){\r\n");
      out.write("\t\tswal('','전송할 파일을 첨부해주세요.','error')\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i = 0; i < $('input[name=\"inspRadioBtn\"]').length; i++){\r\n");
      out.write("\t\tvar map = saveList[i];\r\n");
      out.write("\t\tmap.base64img = imgs[i];\r\n");
      out.write("\t\tsaveList[i] = map;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor(var i = 0; i < saveList.length; i++){\r\n");
      out.write("\t\tvar map = saveList[i];\r\n");
      out.write("\t\tif(map.hasOwnProperty('base64img')){\r\n");
      out.write("\t\t\tif(map.base64img == undefined){\r\n");
      out.write("\t\t\t\tswal('','아직 완료하지 않은 검사가 있습니다.','error')\r\n");
      out.write("\t\t\t\treturn false\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tconsole.log(saveList)\r\n");
      out.write("\t$('html').loading('start');\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'post'\r\n");
      out.write("\t\t, data: {\"saveList\":JSON.stringify(saveList)}\r\n");
      out.write("\t\t, url: '/SaveInspFile'\r\n");
      out.write("\t\t, beforeSend: function (jqXHR, settings) {\r\n");
      out.write("\t\t\t/* ajax 사용시 헤더에 스프링시큐리티 토큰 설정 */\r\n");
      out.write("\t\t\tvar token = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\tvar header = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("\t\t\tjqXHR.setRequestHeader(header, token);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t$('html').loading('stop');\r\n");
      out.write("\t\t\tif(data > 0){\r\n");
      out.write("\t\t\t\tswal('','파일 전송 성공','success');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tswal('','파일 전송 실패','error');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("// \t\t\tconsole.log(data)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function getFormatDate(date){\r\n");
      out.write("    var year = date.getFullYear();              //yyyy\r\n");
      out.write("    var month = (1 + date.getMonth());          //M\r\n");
      out.write("    month = month >= 10 ? month : '0' + month;  //month 두자리로 저장\r\n");
      out.write("    var day = date.getDate();                   //d\r\n");
      out.write("    day = day >= 10 ? day : '0' + day;          //day 두자리로 저장\r\n");
      out.write("    var hours = date.getHours();\r\n");
      out.write("    hours = hours >= 10 ? hours : '0' + hours;\r\n");
      out.write("    var minutes = date.getMinutes();\r\n");
      out.write("    minutes = minutes >= 10 ? minutes : '0' + minutes;\r\n");
      out.write("    var seconds = date.getSeconds();\r\n");
      out.write("    seconds = seconds >= 10 ? seconds : '0' + seconds;\r\n");
      out.write("    return  year + '-' + month + '-' + day + ' ' + hours + ':' + minutes + ':' + seconds;       //'-' 추가하여 yyyy-mm-dd 형태 생성 가능\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("$(document).on(\"click\",\".viewImg\",function(){\r\n");
      out.write("// \talert(\"hi\");\r\n");
      out.write("\t$(\".imgViewDiv\").css(\"display\",\"inline-block\");\r\n");
      out.write("// // // \tvar imgList =\"\";\r\n");
      out.write("// // // \timgList +=\r\n");
      out.write("// \tconsole.log(this)\r\n");
      out.write("\tvar bigImg = $(this).clone(true);\r\n");
      out.write("\tvar imgList=[];\r\n");
      out.write("// \tvar smallImg =\"\";\r\n");
      out.write("\tbigImg.css(\"height\",\"100%\")\r\n");
      out.write("\tbigImg.css(\"width\",\"100%\")\r\n");
      out.write("// \tconsole.log(\"bigImg\",bigImg)\r\n");
      out.write("\t$(\"#viewBigImg\").html(bigImg);\r\n");
      out.write("\tfor(var i=0;i<$(\"#filePlus\").find('img').length;i++){\r\n");
      out.write("\t\tvar smallImg = $(\".viewImg\")[i].cloneNode(true);\r\n");
      out.write("// \t\t//오브젝트 클론 되는지 안되는지 확인하기~~!!\r\n");
      out.write("// \t\tconsole.log(smallImg);\r\n");
      out.write("\t\timgList.push(smallImg);\r\n");
      out.write("// \t\timgList.push($(\"#filePlus\").find('img')[i].clone(true));\r\n");
      out.write("\t}\r\n");
      out.write("// \tconsole.log(\"클래스로 불러온 파일\",$(\".viewImg\")[0])\r\n");
      out.write("// \tconsole.log(\"집어넣은 파일\",$(\"#filePlus\").find('img')[0]);\r\n");
      out.write("// \tconsole.log(\"이미지 파일 반복문으로 가져오기\",imgList)\r\n");
      out.write("// \tconsole.log(\"집어넣은 파일개수\",$(\"#filePlus\").find('img').length);\r\n");
      out.write("\t$(\"#viewImgList\").html(imgList);\r\n");
      out.write("})\t\r\n");
      out.write("$(\"#viewImgClose\").on(\"click\",function(){\r\n");
      out.write("\t$(\".imgViewDiv\").css(\"display\",\"none\");\r\n");
      out.write("})\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
