/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-05-04 05:51:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1644822111181L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_project/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1643079176937L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var csrfParameter = $(\"meta[name=_csrf_parameter]\").attr(\"content\");\n");
      out.write("var csrfHeader = $(\"meta[name=_csrf_header]\").attr(\"content\");\n");
      out.write("var csrfToken = $(\"meta[name=_csrf]\").attr(\"content\");\n");
      out.write("var socket = null;\n");
      out.write("\n");
      out.write("$('html').loading('start');\n");
      out.write("\n");
      out.write("$(function(){\n");
      out.write("\tconnectWs();\n");
      out.write("\t\n");
      out.write("\tfunction connectWs(){\n");
      out.write("\t   \tsock = new SockJS( \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" );\n");
      out.write("\t   \tsocket = sock;\n");
      out.write("\t   \t\n");
      out.write("\t   \tsock.onopen = function() {\n");
      out.write("\t           socket.send('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\t   \t};\n");
      out.write("\n");
      out.write("\t    sock.onerror = function (err) {console.log('Errors : ' , err);};\n");
      out.write("\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t$('html').loading('stop');\n");
      out.write("\t$(\"#searchInput\").autocomplete({\n");
      out.write("\t\tsource : function( request, response ) {\n");
      out.write("             $.ajax({\n");
      out.write("                    type: 'get',\n");
      out.write("                    url: \"/main/searchData\",\n");
      out.write("                   \tdata: {\"data\":$(\"#searchInput\").val()},\n");
      out.write("                    success: function(data) {\n");
      out.write("                        response(\n");
      out.write("                            $.map(data, function(item) {\n");
      out.write("                                return {\n");
      out.write("                                    label: item.nm,\t//UI 에서 보여지는 글자, 실제 검색어랑 비교 대상\n");
      out.write("                                    cd: item.cd,\n");
      out.write("                                    cls : item.cls\n");
      out.write("                                }\n");
      out.write("                            })\n");
      out.write("                        );\n");
      out.write("                    }\n");
      out.write("               });\n");
      out.write("            },\t// source 는 자동 완성 대상\n");
      out.write("\t\tselect : function(event, ui) {\t//아이템 선택시\n");
      out.write("\t\t\tif(ui.item.cls=='환자'){\n");
      out.write("\t\t\t\tlocation.href='/patients/patientsList?keyWord='+ui.item.label;\n");
      out.write("\t\t\t}else if(ui.item.cls=='직원'){\n");
      out.write("\t\t\t\tlocation.href='/profile/'+ui.item.cd;\n");
      out.write("\t\t\t}else if(ui.item.cls=='예약'){\n");
      out.write("\t\t\t\tlocation.href='/reservation/main'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\tfocus : function(event, ui) {\t//포커스 가면\n");
      out.write("\t\t\treturn false;//한글 에러 잡기용도로 사용됨\n");
      out.write("\t\t},\n");
      out.write("\t\tminLength: 1,// 최소 글자수\n");
      out.write("\t\tautoFocus: true, //첫번째 항목 자동 포커스 기본값 false\n");
      out.write("\t\tclasses: {\n");
      out.write("\t\t    \"ui-autocomplete\": \"highlight\"\n");
      out.write("\t\t},\n");
      out.write("\t\tdelay: 100,\t//검색창에 글자 써지고 나서 autocomplete 창 뜰 때 까지 딜레이 시간(ms)\n");
      out.write("\t\tposition: { my : \"left top\", at: \"left bottom\" },\n");
      out.write("\t}).autocomplete( \"instance\" )._renderItem = function( ul, item ) {\n");
      out.write("\t        ul.css(\"background\",\"#f5f7fd\");\n");
      out.write("\t\t\treturn $( \"<li>\" )\n");
      out.write("\t        .append( \"<div>\" + item.cls + \"<br>\" + item.label + \"</div>\" )\n");
      out.write("\t        .appendTo( ul );\n");
      out.write(" \t};\n");
      out.write("\t\n");
      out.write("\tvar secCd = $('#secSelectBox option:selected').val();\n");
      out.write("\tvar empCd = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\n");
      out.write("\tif(empCd!=''){\n");
      out.write("\t\tfn_loadInfo();\n");
      out.write("\t\tloadNotification();\n");
      out.write("\t\t//10초마다 알림 불러오기\n");
      out.write("// \t\tlet notiInterval = setInterval(loadNotification,5000);\n");
      out.write("\t\n");
      out.write("\t\t//직원상태\n");
      out.write("\t\tfunction fn_loadInfo(){\n");
      out.write("\t\t\tvar data = {};\n");
      out.write("\n");
      out.write("\t\t\tdata[csrfParameter]=csrfToken;\n");
      out.write("\t\t    data[\"secCd\"]=secCd;\n");
      out.write("\t\t    data[\"empCd\"]=empCd;\n");
      out.write("\t\t    \n");
      out.write("\t\t    $.ajax({ \n");
      out.write("\t\t\t\turl : \"/main/secEmpList\", \n");
      out.write("\t\t\t\ttype : \"post\", \n");
      out.write("\t\t\t\tdataType : \"html\", \n");
      out.write("\t\t\t\tdata : data, \n");
      out.write("\t\t\t\ttraditional: true,\n");
      out.write("\t\t\t\tsuccess: function(res){\n");
      out.write("\t\t\t\t\tvar html = $(\"<div>\").html(res);\n");
      out.write("\t\t\t\t\tvar contents = html.find(\"div#secEmpList\").html();\n");
      out.write("\t\t\t\t\t$(\"#secEmpListWrap\").html(contents);\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\talert(textStatus)\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction loadNotification(){\n");
      out.write("\t\t\tvar data = {};\n");
      out.write("\n");
      out.write("\t\t\tdata[csrfParameter]=csrfToken;\n");
      out.write("\t\t    data[\"secCd\"]=secCd;\n");
      out.write("\t\t    data[\"empCd\"]=empCd;\n");
      out.write("\t\t    \n");
      out.write("\t\t    //알림 토스트\n");
      out.write("\t\t    $.ajax({ \n");
      out.write("\t\t\t\turl : \"/notification/toast\",\n");
      out.write("\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\tdata : data, \n");
      out.write("\t\t\t\tsuccess: function(res){\n");
      out.write("\t\t\t\t\t$.each(res,function(i,v){\n");
      out.write("\t\t\t\t\t\ttoastr.options.escapeHtml = true;\n");
      out.write("\t\t\t\t\t\ttoastr.options.closeButton = true;\n");
      out.write("\t\t\t\t\t\ttoastr.options.newestOnTop = false;\n");
      out.write("\t\t\t\t\t\ttoastr.options.progressBar = true;\n");
      out.write("\t\t\t\t\t\ttoastr.options.onclick = function() {\n");
      out.write("\t\t\t\t\t\t\tdata[\"notNo\"]=v.notNo;\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$.ajax({ \n");
      out.write("\t\t\t\t\t\t\t\turl : \"/notification/click\", \n");
      out.write("\t\t\t\t\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\t\t\t\t\tdata : data,\n");
      out.write("\t\t\t\t\t\t\t\tsuccess: function(res){\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation.href = v.notUrl;\n");
      out.write("\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\t\t\t\t\talert(textStatus)\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t\tif(v.cmCd=='NS1'){\n");
      out.write("\t\t\t\t\t\t\ttoastr.info(v.notDt, v.opt, {timeOut: 7500});\n");
      out.write("\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\ttoastr.info(v.notDt, v.pntNm + ' 님이 ' + v.opt, {timeOut: 7500});\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\talert(textStatus)\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t    \n");
      out.write("\t\t    //알림 div에 찍기\n");
      out.write("\t\t    $.ajax({ \n");
      out.write("\t\t\t\turl : \"/notification/list\", \n");
      out.write("\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\tdata : data,\n");
      out.write("\t\t\t\tdataType : \"html\",\n");
      out.write("\t\t\t\tsuccess: function(res){\n");
      out.write("\t\t\t\t\tvar html = $(\"<div>\").html(res);\n");
      out.write("\t\t\t\t\tvar contents = html.find(\"div#ajaxData\").html();\n");
      out.write("\t\t\t\t\t$(\"#notification\").html(contents);\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\talert(textStatus)\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t$(\"#secSelectBox\").on(\"change\",function(){\n");
      out.write("\t\tsecCd = $('option:selected',this).attr('value');\n");
      out.write("\t\tfn_loadInfo();\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t$(document).on('click',\"#allRead\",function(){\n");
      out.write("\t\t$.ajax({ \n");
      out.write("\t\t\turl : \"/notification/allRead\", \n");
      out.write("\t\t\ttype : \"post\",\n");
      out.write("\t\t\tdata : {\"empCd\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"},\n");
      out.write("\t\t\tbeforeSend: function (jqXHR, settings) {\n");
      out.write("\t\t\t\t/* ajax 사용시 헤더에 스프링시큐리티 토큰 설정 */\n");
      out.write("\t\t\t\tvar token = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\n");
      out.write("\t\t\t\tvar header = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\n");
      out.write("\t\t\t\tjqXHR.setRequestHeader(header, token);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess: function(res){\n");
      out.write("// \t\t\t\t$(\"#notification\").empty();\n");
      out.write("\t\t\t\tloadNotification();\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\t\talert(textStatus)\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\tvar searchInput = $(\"#searchInput\");\n");
      out.write("\tsearchInput.focus(function(){\n");
      out.write("\t\t$(\".searchBox\").prop(\"hidden\",false);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t/*알림 클릭*/\n");
      out.write("\t$(\".notification_info a\").on(\"click\", function(){\n");
      out.write("\t\t$(\".notification_info_iner.notification\").addClass(\"on\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t/*알림 닫기버튼 클릭*/\n");
      out.write("\t$(\".notification_info .notification button.btn-close\").on(\"click\",function(){\n");
      out.write("\t\t$(\".notification_info_iner.notification\").removeClass(\"on\");\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t\n");
      out.write("})\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function fn_clickNotification(t){\n");
      out.write("\tconsole.log(t.id)\n");
      out.write("\tconsole.log(t.name)\n");
      out.write("\tvar data = {};\n");
      out.write("\n");
      out.write("\tdata[csrfParameter]=csrfToken;\n");
      out.write("\tdata[\"notNo\"]=t.id;\n");
      out.write("\t\n");
      out.write("\t$.ajax({ \n");
      out.write("\t\turl : \"/notification/click\", \n");
      out.write("\t\ttype : \"post\",\n");
      out.write("\t\tdata : data,\n");
      out.write("\t\tsuccess: function(res){\n");
      out.write("\t\t\tlocation.href = t.name;\n");
      out.write("\t\t},\n");
      out.write("\t\terror: function(jqXHR, textStatus, errorThrown){\n");
      out.write("\t\t\talert(textStatus)\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("function fn_logout(){\n");
      out.write("\tdocument.getElementById('logoutFrm').submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function fn_showInfo(t){\n");
      out.write("\t$(t).next().prop(\"hidden\",false);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function fn_closeInfo(t){\n");
      out.write("\t$(t).next().prop(\"hidden\",true);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write(".tooltip-table{\n");
      out.write("\tbackground-color: #2e4765;\n");
      out.write("\tposition:absolute;\n");
      out.write("\tright: 180px;\n");
      out.write("\ttop: 200px;\n");
      out.write("\tmargin: 50px; \n");
      out.write("\tpadding: 20px; \n");
      out.write("\twidth:300px;\n");
      out.write("\tborder-radius: 10px;\n");
      out.write("\theight: auto;\n");
      out.write("}\n");
      out.write(".tooltip-table:after{\n");
      out.write("\tcontent:\"\"; \n");
      out.write("\tposition: absolute; \n");
      out.write("\ttop: 21px; \n");
      out.write("\tright: -30px; \n");
      out.write("\tborder-left: 30px solid #2e4765; \n");
      out.write("\tborder-top: 10px solid transparent; \n");
      out.write("\tborder-bottom: 10px solid transparent;\n");
      out.write("}\n");
      out.write(".tooltip-table table{\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\twidth: 260px;\n");
      out.write("\tcolor: #eff1f7;\n");
      out.write("\ttext-align: right;\n");
      out.write("}\n");
      out.write(".tooltip-table table tr :nth-child(1){\n");
      out.write("\twidth: 20%;\n");
      out.write("}\n");
      out.write(".tooltip-table table tr :nth-child(2){\n");
      out.write("\twidth: 78%;\n");
      out.write("}\n");
      out.write(".notification li a {\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write(".hide {\n");
      out.write("  \tdisplay: none !important;\t/* 사용자가 아무것도 입력하지 않았을 때 검색창을 숨기는 용도*/\n");
      out.write("}\n");
      out.write(".rel_search {\n");
      out.write("\tdisplay:flex;\n");
      out.write("\tflex-direction:column;\n");
      out.write("\tjustify-content : space-around;\n");
      out.write("\tborder-radius: 12px;\n");
      out.write("\tbackground: #f5f7fd;\n");
      out.write("\tz-index: 10;\n");
      out.write("}\n");
      out.write(".pop_rel_keywords {\n");
      out.write("  list-style: none;\n");
      out.write("  margin-right: 30%;\n");
      out.write("}\n");
      out.write(".pop_rel_keywords > li {\t/* JS에서 동적으로 li를 생성할 때 적용될 스타일*/\n");
      out.write("  line-height : 250%\n");
      out.write("}\n");
      out.write(".empList{\n");
      out.write("\tmargin: -15px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<div id=\"header\" class=\"container-fluid no-gutters\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"col-lg-12 p-0\">\n");
      out.write("\t\t\t<div class=\"header_iner d-flex justify-content-between align-items-center\">\n");
      out.write("\t\t\t\t<div class=\"sidebar_icon d-lg-none\">\n");
      out.write("\t\t\t\t\t<i class=\"ti-menu\"></i>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"serach_field-area\">\n");
      out.write("\t\t\t\t\t<div class=\"search_inner\">\n");
      out.write("\t\t\t\t\t\t<form action=\"#\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search_field\">\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"searchInput\" type=\"text\" placeholder=\"검색\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/resources/img/icon/icon_search.svg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- 로그인 하지 않은 경우 true -->\n");
      out.write("                ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                \n");
      out.write("                <!-- 로그인 시 -->\n");
      out.write("                ");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/tiles/header.jsp(17,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/echo");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/tiles/header.jsp(332,16) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("                <div class=\"header_right d-flex justify-content-between align-items-center\">\n");
        out.write("                \t<div class=\"header_notification_warp d-flex align-items-center\">\n");
        out.write("                \t\t<div class=\"notification_info\">\n");
        out.write("\t\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/img/icon/bell.svg\" alt=\"\"></a>\n");
        out.write("\t\t\t\t\t\t\t<div id=\"notification\" class=\"notification_info_iner notification white_box shadow\">\n");
        out.write("\t\t\t\t\t\t\t\t<!-- 알림 영역 -->\n");
        out.write("\t\t\t\t\t\t\t\t<ul class=\"list-group list-group-flush\">\n");
        out.write("\t\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\n");
        out.write("\t\t\t\t\t\t\t\t    \t<a href=\"/login\"><span class=\"text-info mr-2\">로그인 해주세요</span></a>\n");
        out.write("\t\t\t\t\t\t\t\t  \t</li>\n");
        out.write("\t\t\t\t\t\t\t\t</ul>\n");
        out.write("\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t</div>\n");
        out.write("                \t</div>\n");
        out.write("                \t<div class=\"profile_info\">\n");
        out.write("                \t\t<img src=\"/resources/img/client_img.png\" alt=\"#\">\n");
        out.write("                \t\t<div class=\"profile_info_iner\">\n");
        out.write("\t\t\t\t\t\t\t<a href=\"/login\"><h5><i class=\"ti-user\"></i>로그인 해주세요</h5></a>\n");
        out.write("\t\t\t\t\t\t</div>\n");
        out.write("                \t</div>\n");
        out.write("\t\t\t\t</div>\n");
        out.write("                ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/tiles/header.jsp(357,16) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t                ");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t                ");
        if (_jspx_meth_sec_005fauthentication_005f1(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t                ");
        if (_jspx_meth_sec_005fauthentication_005f2(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t                ");
        if (_jspx_meth_sec_005fauthentication_005f3(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t                ");
        if (_jspx_meth_sec_005fauthentication_005f4(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t                <input type=\"hidden\" id=\"checkLogin\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("\t\t\t\t<div class=\"header_right d-flex justify-content-between align-items-center\">\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthorize_005f2(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t<div class=\"profile_info\">\n");
        out.write("\t\t\t\t\t\t<img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" alt=\"#\">\n");
        out.write("\t\t\t\t\t\t<div class=\"profile_info_iner\">\n");
        out.write("\t\t\t\t\t\t\t<p>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${secNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\n");
        out.write("\t\t\t\t\t\t\t<h5>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</h5>\n");
        out.write("\t\t\t\t\t\t\t<div class=\"profile_info_details\">\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthorize_005f3(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("<!-- \t\t\t\t\t\t\t\t<a href=\"#\">Settings<i class=\"ti-settings\"></i></a> -->\n");
        out.write("\t\t\t\t\t\t\t\t<form id=\"logoutFrm\" action=\"/logout\" method=\"post\">\n");
        out.write("\t\t\t                    \t");
        if (_jspx_meth_sec_005fcsrfInput_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t                    <a href=\"javascript:fn_logout()\">Log Out <i class=\"ti-shift-left\"></i></a>\n");
        out.write("\t\t\t                    </form>\n");
        out.write("\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t\t");
        if (_jspx_meth_sec_005fauthorize_005f4(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t</div>\n");
        out.write("\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(358,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.user.empPic");
      // /WEB-INF/views/tiles/header.jsp(358,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("empPic");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(359,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.user.empCd");
      // /WEB-INF/views/tiles/header.jsp(359,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setVar("empCd");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f2 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(360,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f2.setProperty("principal.user.empNm");
      // /WEB-INF/views/tiles/header.jsp(360,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f2.setVar("empNm");
      int _jspx_eval_sec_005fauthentication_005f2 = _jspx_th_sec_005fauthentication_005f2.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f2);
      _jspx_th_sec_005fauthentication_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f3 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(361,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f3.setProperty("principal.user.secCd");
      // /WEB-INF/views/tiles/header.jsp(361,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f3.setVar("secCd");
      int _jspx_eval_sec_005fauthentication_005f3 = _jspx_th_sec_005fauthentication_005f3.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f3);
      _jspx_th_sec_005fauthentication_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f4 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f4_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(362,17) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f4.setProperty("principal.user.secNm");
      // /WEB-INF/views/tiles/header.jsp(362,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f4.setVar("secNm");
      int _jspx_eval_sec_005fauthentication_005f4 = _jspx_th_sec_005fauthentication_005f4.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f4);
      _jspx_th_sec_005fauthentication_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f4, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(365,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setAccess("hasAnyRole(\"ROLE_DOCTOR\",\"ROLE_NURSE\",\"ROLE_ENGI\",\"ROLE_WONMU\")");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t<div class=\"header_notification_warp d-flex align-items-center\">\n");
        out.write("\t\t\t\t\t\t\t<div class=\"notification_info\">\n");
        out.write("\t\t\t\t\t\t\t\t<a href=\"#\"> <img src=\"/resources/img/icon/bell.svg\" alt=\"\"></a>\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"notification_info_iner notification white_box shadow\">\n");
        out.write("\t\t\t\t\t\t\t\t\t<!-- 알림 영역(알림이 많을 경우 화면이 넘어가지 않게 스크롤 처리함) -->\n");
        out.write("\t\t\t\t\t\t\t\t\t\n");
        out.write("\t\t\t\t\t\t\t\t\t<div id=\"notification\" class=\"notification_info_iner notification white_box shadow\"\n");
        out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"max-height: 500px; overflow: auto;\">\n");
        out.write("\t\t\t\t\t\t\t\t\t\n");
        out.write("\t\t\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-close\">닫기</button>\n");
        out.write("\t\t\t\t\t\t\t\t\t<button id=\"allRead\" type=\"button\" class=\"btn btn-sm btn-danger\" style=\"float:right;\">전체 읽음 처리</button>\n");
        out.write("\t\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(388,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setAccess("hasAnyRole(\"ROLE_DOCTOR\",\"ROLE_NURSE\",\"ROLE_ENGI\",\"ROLE_WONMU\")");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t<a href=\"/profile/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">My Profile <i class=\"ti-user\"></i></a>\n");
        out.write("\t\t\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f3, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fcsrfInput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:csrfInput
    org.springframework.security.taglibs.csrf.CsrfInputTag _jspx_th_sec_005fcsrfInput_005f0 = (org.springframework.security.taglibs.csrf.CsrfInputTag) _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfInputTag.class);
    boolean _jspx_th_sec_005fcsrfInput_005f0_reused = false;
    try {
      _jspx_th_sec_005fcsrfInput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fcsrfInput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      int _jspx_eval_sec_005fcsrfInput_005f0 = _jspx_th_sec_005fcsrfInput_005f0.doStartTag();
      if (_jspx_th_sec_005fcsrfInput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.reuse(_jspx_th_sec_005fcsrfInput_005f0);
      _jspx_th_sec_005fcsrfInput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fcsrfInput_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fcsrfInput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f4 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f4_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/header.jsp(397,7) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f4.setAccess("hasAnyRole(\"ROLE_DOCTOR\",\"ROLE_NURSE\",\"ROLE_ENGI\",\"ROLE_WONMU\")");
      int _jspx_eval_sec_005fauthorize_005f4 = _jspx_th_sec_005fauthorize_005f4.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t\t<div class=\"profile_info_details\">\n");
        out.write("\t\t\t\t\t\t\t\t<h5>\n");
        out.write("\t\t\t\t\t\t\t\t\t<select id=\"secSelectBox\">\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${secCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" selected>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${secNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_sec_005fauthorize_005f4, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t\t</select>\n");
        out.write("\t\t\t\t\t\t\t\t</h5>\n");
        out.write("\t\t\t\t\t\t\t\t<!-- 자기 팀 상태 -->\n");
        out.write("\t\t\t\t\t\t\t\t<div id=\"secEmpListWrap\">\n");
        out.write("\t\t\t\t\t\t\t\t\t\n");
        out.write("\t\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t\t</div>\n");
        out.write("\t\t\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f4);
      _jspx_th_sec_005fauthorize_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f4, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f4);
      // /WEB-INF/views/tiles/header.jsp(402,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("op");
      // /WEB-INF/views/tiles/header.jsp(402,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/tiles/header.jsp(402,10) '${secSelectBox}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${secSelectBox}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${op.secCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${op.secNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
